/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Usuario;
import dao.UsuarioDao;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Kemu27
 */
public class Tela_Cad_Usuario extends javax.swing.JFrame {

    Usuario mod = new Usuario();
    UsuarioDao cadastro = new UsuarioDao();
    dao.Conectar conectar = new dao.Conectar();

   
    /**
     * Creates new form Tela_Cad_Usuario
     */
    public Tela_Cad_Usuario() {
        conectar.conexao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Tela_Cad_Usuario_fundo = new javax.swing.JPanel();
        Matri_Tela_Cad_Usuario_Mat = new javax.swing.JLabel();
        Nome_Tela_Cad_Usuario_Nome = new javax.swing.JLabel();
        Senha_Tela_Cad_Usuario_Senha = new javax.swing.JLabel();
        JlabelTipo_TIpo = new javax.swing.JLabel();
        JTexFieldPesquisar = new javax.swing.JTextField();
        Nome_Tela_Cad_Usuario_usuario = new javax.swing.JLabel();
        JTexFieldMatricula = new javax.swing.JTextField();
        JTexFieldNome = new javax.swing.JTextField();
        JTexFieldSenha = new javax.swing.JPasswordField();
        JComboBoxTipo = new javax.swing.JComboBox();
        JTexFieldUsuário = new javax.swing.JTextField();
        JButtonCancelar = new javax.swing.JButton();
        JButtonExcluir = new javax.swing.JButton();
        JButtonNovo = new javax.swing.JButton();
        JButtonAlterar = new javax.swing.JButton();
        JButtonSalvar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();
        JlabelUsuário = new javax.swing.JLabel();
        jLabelfundotituloUsuario = new javax.swing.JLabel();
        jLabelPlanodefundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Painel_Tela_Cad_Usuario_fundo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Painel_Tela_Cad_Usuario_fundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Matri_Tela_Cad_Usuario_Mat.setBackground(new java.awt.Color(0, 51, 255));
        Matri_Tela_Cad_Usuario_Mat.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 15)); // NOI18N
        Matri_Tela_Cad_Usuario_Mat.setText("Matrícula");
        Painel_Tela_Cad_Usuario_fundo.add(Matri_Tela_Cad_Usuario_Mat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        Nome_Tela_Cad_Usuario_Nome.setBackground(new java.awt.Color(0, 51, 255));
        Nome_Tela_Cad_Usuario_Nome.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 15)); // NOI18N
        Nome_Tela_Cad_Usuario_Nome.setText("Nome");
        Painel_Tela_Cad_Usuario_fundo.add(Nome_Tela_Cad_Usuario_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        Senha_Tela_Cad_Usuario_Senha.setBackground(new java.awt.Color(0, 51, 255));
        Senha_Tela_Cad_Usuario_Senha.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 15)); // NOI18N
        Senha_Tela_Cad_Usuario_Senha.setText("Senha");
        Painel_Tela_Cad_Usuario_fundo.add(Senha_Tela_Cad_Usuario_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        JlabelTipo_TIpo.setBackground(new java.awt.Color(0, 51, 255));
        JlabelTipo_TIpo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 15)); // NOI18N
        JlabelTipo_TIpo.setText("Tipo");
        Painel_Tela_Cad_Usuario_fundo.add(JlabelTipo_TIpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 30));
        Painel_Tela_Cad_Usuario_fundo.add(JTexFieldPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 280, 31));

        Nome_Tela_Cad_Usuario_usuario.setBackground(new java.awt.Color(0, 51, 255));
        Nome_Tela_Cad_Usuario_usuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 15)); // NOI18N
        Nome_Tela_Cad_Usuario_usuario.setText("Usuário");
        Painel_Tela_Cad_Usuario_fundo.add(Nome_Tela_Cad_Usuario_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        JTexFieldMatricula.setEnabled(false);
        Painel_Tela_Cad_Usuario_fundo.add(JTexFieldMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 124, 31));

        JTexFieldNome.setEnabled(false);
        Painel_Tela_Cad_Usuario_fundo.add(JTexFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 363, 31));

        JTexFieldSenha.setEnabled(false);
        Painel_Tela_Cad_Usuario_fundo.add(JTexFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 360, 31));

        JComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador\t", "Usuário Padrão", " " }));
        Painel_Tela_Cad_Usuario_fundo.add(JComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 119, 31));
        Painel_Tela_Cad_Usuario_fundo.add(JTexFieldUsuário, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, 31));

        JButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtonCancelar.setText("Cancelar");
        JButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCancelarActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Usuario_fundo.add(JButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 84, 33));

        JButtonExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtonExcluir.setText("Excluir");
        JButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonExcluirActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Usuario_fundo.add(JButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 84, 33));

        JButtonNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtonNovo.setText("Novo");
        JButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonNovoActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Usuario_fundo.add(JButtonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 84, 33));

        JButtonAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtonAlterar.setText("Alterar");
        JButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAlterarActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Usuario_fundo.add(JButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 84, 33));

        JButtonSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtonSalvar.setText("Salvar");
        JButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSalvarActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Usuario_fundo.add(JButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 84, 33));

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Usuario_fundo.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 80, 30));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/fundo_2.png"))); // NOI18N
        Painel_Tela_Cad_Usuario_fundo.add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 420));

        //Painel_Tela_Cad_Usuario.setGlassPane(meuGlassPane);

        getContentPane().add(Painel_Tela_Cad_Usuario_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 740, 420));

        JlabelUsuário.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JlabelUsuário.setForeground(new java.awt.Color(255, 255, 255));
        JlabelUsuário.setText("Cadastro de Usuário");
        getContentPane().add(JlabelUsuário, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabelfundotituloUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/azul.jpg"))); // NOI18N
        getContentPane().add(jLabelfundotituloUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 60));

        jLabelPlanodefundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/user.jpg"))); // NOI18N
        getContentPane().add(jLabelPlanodefundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, 0, 1300, 550));

        setSize(new java.awt.Dimension(972, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LimparCampos() {
        JTexFieldMatricula.setText("");
        JTexFieldNome.setText("");
        JTexFieldUsuário.setText("");
        JTexFieldSenha.setText("");
        JTexFieldMatricula.setText("");
        JTexFieldUsuário.setText("");
    }

    private void JButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSalvarActionPerformed

        if (JTexFieldUsuário.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o Usuário para continuar");
            JTexFieldUsuário.requestFocus();

        } else if (JTexFieldSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a Senha para continuar");
            JTexFieldSenha.requestFocus();
        }
        mod.setNome(JTexFieldNome.getText());
        mod.setUsuario(JTexFieldUsuário.getText());
        mod.setSenha(JTexFieldSenha.getText());
        mod.setMatricula(Integer.parseInt(JTexFieldMatricula.getText()));
        mod.setTipo((String) JComboBoxTipo.getSelectedItem());

        cadastro.Salvar(mod);
        LimparCampos();

        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonSalvarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        JTexFieldMatricula.setEnabled(false);
        JTexFieldNome.setEnabled(true);
        JTexFieldUsuário.setEnabled(true);
        JTexFieldSenha.setEnabled(true);
        JComboBoxTipo.setEnabled(true);
        JTexFieldUsuário.setEnabled(true);

        UsuarioDao userdao = new UsuarioDao();
        Usuario a = new Usuario();

        String busca = JTexFieldUsuário.getText();
        String nome = JTexFieldNome.getText();
        String usuario = JTexFieldUsuário.getText();
        String senha = JTexFieldSenha.getText();
        String tipo = (String) JComboBoxTipo.getSelectedItem();

        a = userdao.Buscar(busca);

        if (a != null) {
            JTexFieldNome.setText(a.getNome());
            JTexFieldUsuário.setText(a.getUsuario());
            JTexFieldMatricula.setText(a.getMatricula().toString());
            JComboBoxTipo.setSelectedItem(a.getTipo());
            JTexFieldSenha.setText(a.getSenha());

        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuario Não Encontrado");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void JButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCancelarActionPerformed
       LimparCampos();
    }//GEN-LAST:event_JButtonCancelarActionPerformed

    private void JButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAlterarActionPerformed
          UsuarioDao adao = new UsuarioDao();
        Usuario a = new Usuario();
        
        String nome = JTexFieldNome.getText();
        String usuario = JTexFieldUsuário.getText();
        String senha = JTexFieldSenha.getText();
       
        //UsuarioDao userdao = new UsuarioDao();
        a.setNome(nome);
        a.setSenha(senha);
        a.setTipo(nome);
        a.setUsuario(usuario);
        
        cadastro.Alterar(a);
        LimparCampos();
    }//GEN-LAST:event_JButtonAlterarActionPerformed

    private void JButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonNovoActionPerformed
      
        JTexFieldMatricula.setEnabled(true);
        JTexFieldNome.setEnabled(true);
        JTexFieldUsuário.setEnabled(true);
        JTexFieldSenha.setEnabled(true);
        JTexFieldMatricula.setEnabled(true);
        JComboBoxTipo.setEnabled(true);
        LimparCampos();
    }//GEN-LAST:event_JButtonNovoActionPerformed

    private void JButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonExcluirActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cad_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cad_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cad_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cad_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cad_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAlterar;
    private javax.swing.JButton JButtonCancelar;
    private javax.swing.JButton JButtonExcluir;
    private javax.swing.JButton JButtonNovo;
    private javax.swing.JButton JButtonSalvar;
    private javax.swing.JComboBox JComboBoxTipo;
    private javax.swing.JTextField JTexFieldMatricula;
    private javax.swing.JTextField JTexFieldNome;
    private javax.swing.JTextField JTexFieldPesquisar;
    private javax.swing.JPasswordField JTexFieldSenha;
    private javax.swing.JTextField JTexFieldUsuário;
    private javax.swing.JLabel JlabelTipo_TIpo;
    private javax.swing.JLabel JlabelUsuário;
    private javax.swing.JLabel Matri_Tela_Cad_Usuario_Mat;
    private javax.swing.JLabel Nome_Tela_Cad_Usuario_Nome;
    private javax.swing.JLabel Nome_Tela_Cad_Usuario_usuario;
    private javax.swing.JPanel Painel_Tela_Cad_Usuario_fundo;
    private javax.swing.JLabel Senha_Tela_Cad_Usuario_Senha;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelPlanodefundo;
    private javax.swing.JLabel jLabelfundotituloUsuario;
    // End of variables declaration//GEN-END:variables
}
